/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffba20",
        "surface-container-lowest": "#0b0e14",
        "inverse-surface": "#e1e2eb",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "tertiary": "#47d6ff",
        "secondary-container": "#feb700",
        "on-tertiary-container": "#eefaff",
        "surface-container": "#1d2026",
        "tertiary-fixed-dim": "#47d6ff",
        "inverse-on-surface": "#2e3037",
        "tertiary-container": "#007c98",
        "background": "#10131a",
        "primary-fixed": "#dae1ff",
        "on-secondary-fixed-variant": "#5e4200",
        "surface-bright": "#363940",
        "on-background": "#e1e2eb",
        "on-surface": "#e1e2eb",
        "on-primary": "#002b75",
        "on-primary-fixed": "#001849",
        "surface": "#10131a",
        "on-primary-container": "#f8f7ff",
        "surface-variant": "#32353c",
        "on-secondary-fixed": "#271900",
        "surface-container-highest": "#32353c",
        "on-surface-variant": "#c2c6d8",
        "primary": "#b3c5ff",
        "outline-variant": "#424656",
        "surface-container-low": "#191c22",
        "primary-container": "#0066ff",
        "on-tertiary": "#003543",
        "inverse-primary": "#0054d6",
        "secondary": "#ffdb9d",
        "on-error": "#690005",
        "surface-tint": "#b3c5ff",
        "surface-container-high": "#272a31",
        "secondary-fixed": "#ffdea8",
        "surface-dim": "#10131a",
        "on-primary-fixed-variant": "#003fa4",
        "tertiary-fixed": "#b6ebff",
        "error": "#ffb4ab",
        "on-secondary-container": "#6b4b00",
        "on-tertiary-fixed": "#001f28",
        "on-secondary": "#412d00",
        "outline": "#8c90a1",
        "primary-fixed-dim": "#b3c5ff",
        "on-tertiary-fixed-variant": "#004e60"
      },
      // ── Design Token Spacing Scale (matches original CDN config exactly) ──
      spacing: {
        "container-max": "1280px",
        "base": "4px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "40px",
        "xl": "80px",
        "gutter": "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      // ── Border Radius Scale ──
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      // ── Typography Scale (matches original CDN fontSize config) ──
      fontSize: {
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "900" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "mono-data": ["14px", { lineHeight: "1.5", fontWeight: "500" }],
      },
      fontFamily: {
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "mono-data": ["Geist", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "monospace"],
        "display-xl": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "display": ["Montserrat", "sans-serif"],
      },
    },
  },
  plugins: [],
}
